Update workflow

diff --git a/.github/workflows/mediajira-ci-preview.yml b/.github/workflows/mediajira-ci-preview.yml
--- a/.github/workflows/mediajira-ci-preview.yml
+++ b/.github/workflows/mediajira-ci-preview.yml
@@ -7,7 +7,20 @@ on:
     branches: [prod-preview]
 
 jobs:
+  block:
+    if: github.event.pull_request.base.ref == 'prod-preview'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check source branch
+        run: |
+          if [ "${{ github.head_ref }}" == "prod-preview" ]; then
+            echo "prod-preview branch cannot open PRs to itself. Please use a different source branch."
+            exit 1
+          fi
+          echo "Source branch ${{ github.head_ref }} is allowed to PR to prod-preview."
+
   code_scan:
+    needs: block
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -85,6 +98,7 @@ jobs:
             devops/npm-audit/*report*
             devops/gitleaks/*report*
   image_scan:
+    needs: block
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -146,6 +160,7 @@ jobs:
           path: |
             devops/trivy/*report*
   application_test:
+    needs: block
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -320,7 +335,7 @@ jobs:
           docker system prune -f
 
   deploy:
-    needs: [code_scan, image_scan, application_test]
+    needs: [block, code_scan, image_scan, application_test]
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/prod-preview' && (github.event_name == 'push' || github.event_name == 'pull_request')
     steps:
@@ -337,18 +352,20 @@ jobs:
         run: |
           curl -X POST https://24mf5mvg7g.execute-api.ap-southeast-2.amazonaws.com/default/Auto-Deploy-mediajira-preview -H "Content-Type: application/json" -d '{"action": "deploy", "source": "github"}'
   notify:
-    needs: [code_scan, image_scan, application_test, deploy]
+    needs: [block, code_scan, image_scan, application_test, deploy]
     runs-on: ubuntu-latest
     if: always()
     steps:
       - name: Send Discord notification
         run: |
+          BLOCK="${{ needs.block.result }}"
           CODE_SCAN="${{ needs.code_scan.result }}"
           IMAGE_SCAN="${{ needs.image_scan.result }}"
           APPLICATION_TEST="${{ needs.application_test.result }}"
           DEPLOY="${{ needs.deploy.result }}"
           STATUS="${{ job.status }}"
           MESSAGE="Workflow *${{ github.workflow }}* finished on branch *${{ github.ref_name }}*\n"
+          MESSAGE+="Block: **$BLOCK**\n"
           MESSAGE+="Code scan: **$CODE_SCAN**\n"
           MESSAGE+="Image scan: **$IMAGE_SCAN**\n"
           MESSAGE+="Application test: **$APPLICATION_TEST**\n"
