fix gitleak

diff --git a/.github/workflows/mediajira-ci.yml b/.github/workflows/mediajira-ci.yml
--- a/.github/workflows/mediajira-ci.yml
+++ b/.github/workflows/mediajira-ci.yml
@@ -108,7 +108,8 @@ jobs:
         continue-on-error: true
         run: |      
           mkdir -p devops/gitleaks
-          for i in backend devops docs frontend k6 nginx openapi pgbackrest postgres; do echo ${i};gitleaks detect --config devops/gitleaks/.gitleaks.toml --source ${i} --report-path devops/gitleaks/gitleaks-report.${i}.json --no-git || echo "gitleaks failed";done
+          ls -la frontend
+          #for i in backend devops docs frontend k6 nginx openapi pgbackrest postgres; do echo ${i};gitleaks detect --config devops/gitleaks/.gitleaks.toml --source ${i} --report-path devops/gitleaks/gitleaks-report.${i}.json --no-git || echo "gitleaks failed";done
 
       - name: Check Dockerfile for USER directive
         run: |
