fix gitleak

diff --git a/.github/workflows/mediajira-ci.yml b/.github/workflows/mediajira-ci.yml
--- a/.github/workflows/mediajira-ci.yml
+++ b/.github/workflows/mediajira-ci.yml
@@ -108,8 +108,7 @@ jobs:
         continue-on-error: true
         run: |      
           mkdir -p devops/gitleaks
-          ls -la
-          # gitleaks detect --config devops/gitleaks/.gitleaks.toml --source . --report-path devops/gitleaks/gitleaks-report.json --no-git || echo "gitleaks failed"
+          gitleaks detect --config devops/gitleaks/.gitleaks.toml --source . --report-path devops/gitleaks/gitleaks-report.json --no-git || echo "gitleaks failed"
 
       - name: Check Dockerfile for USER directive
         run: |
