Implementation of Prometheus and Grafana

diff --git a/.github/workflows/mediajira-ci.yml b/.github/workflows/mediajira-ci.yml
--- a/.github/workflows/mediajira-ci.yml
+++ b/.github/workflows/mediajira-ci.yml
@@ -29,10 +29,10 @@ jobs:
       - name: Run Bandit scan
         continue-on-error: true
         run: |
-          mkdir -p ci_security/bandit
-          bandit -r backend -c ci_security/bandit/bandit.yaml -f html -o ci_security/bandit/bandit-report.html --severity-level medium
+          mkdir -p devops/bandit
+          bandit -r backend -c devops/bandit/bandit.yaml -f html -o devops/bandit/bandit-report.html --severity-level medium
 
-          SEVERITY=$(grep -c Severity ci_security/bandit/bandit-report.html || true)
+          SEVERITY=$(grep -c Severity devops/bandit/bandit-report.html || true)
           if [ $SEVERITY -gt 0 ]; then
             echo "Bandit found $SEVERITY medium/high severity issues."
           fi
@@ -40,16 +40,16 @@ jobs:
       - name: Run pip-audit and npm audit scan
         continue-on-error: true
         run: |
-          mkdir -p ci_security/{pip-audit,npm-audit}
-          pip-audit -r backend/requirements.txt -f json -o ci_security/pip-audit/pip-audit-report-raw.json || echo "pip-audit failed"
-          cat ci_security/pip-audit/pip-audit-report-raw.json | python -m json.tool > ci_security/pip-audit/pip-audit-report.json || echo "json formatting failed"
-          npm audit --prefix frontend --json > ci_security/npm-audit/npm-audit-report.json || echo "npm audit failed"
+          mkdir -p devops/{pip-audit,npm-audit}
+          pip-audit -r backend/requirements.txt -f json -o devops/pip-audit/pip-audit-report-raw.json || echo "pip-audit failed"
+          cat devops/pip-audit/pip-audit-report-raw.json | python -m json.tool > devops/pip-audit/pip-audit-report.json || echo "json formatting failed"
+          npm audit --prefix frontend --json > devops/npm-audit/npm-audit-report.json || echo "npm audit failed"
 
       - name: Run gitleaks scan
         continue-on-error: true
         run: |      
-          mkdir -p ci_security/gitleaks
-          gitleaks detect --config ci_security/gitleaks/.gitleaks.toml --source . --report-path ci_security/gitleaks/gitleaks-report.json --no-git || echo "gitleaks failed"
+          mkdir -p devops/gitleaks
+          gitleaks detect --config devops/gitleaks/.gitleaks.toml --source . --report-path devops/gitleaks/gitleaks-report.json --no-git || echo "gitleaks failed"
 
       - name: Check Dockerfile for USER directive
         run: |
@@ -69,7 +69,7 @@ jobs:
 
       - name: Terraform check
         run: |
-          cd infra/terraform
+          cd devops/infra/terraform
           terraform init -backend=false
           terraform fmt -check -recursive
           terraform validate
@@ -111,15 +111,15 @@ jobs:
       - name: Run Trivy scan (backend)
         continue-on-error: true
         run: |
-          mkdir -p ci_security/trivy
-          trivy image --exit-code 0 --severity HIGH,CRITICAL --format json -o ci_security/trivy/trivy-backend-report.json mediajira-backend:${{ github.sha }}
+          mkdir -p devops/trivy
+          trivy image --exit-code 0 --severity HIGH,CRITICAL --format json -o devops/trivy/trivy-backend-report.json mediajira-backend:${{ github.sha }}
 
 
       # Run Trivy scan for frontend image
       - name: Run Trivy scan (frontend)
         continue-on-error: true
         run: |
-          trivy image --exit-code 0 --severity HIGH,CRITICAL --format json -o ci_security/trivy/trivy-frontend-report.json mediajira-frontend:${{ github.sha }}
+          trivy image --exit-code 0 --severity HIGH,CRITICAL --format json -o devops/trivy/trivy-frontend-report.json mediajira-frontend:${{ github.sha }}
 
       - name: Upload report
         if: always()
@@ -127,7 +127,7 @@ jobs:
         with: 
           name: security-reports-${{ github.sha }}
           path: |
-            ci_security/*/*report*
+            devops/*/*report*
 
       # Create a CI environment file with the necessary environment variables
       # Django secret key is generated based on the current commit hash
